# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- ADIÇÃO: preparar Node para gerar projects.json ---
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- ADIÇÃO: gerar projects.json (não precisa dar commit) ---
      - name: Generate projects.json
        run: node scripts/generate-projects.mjs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   # envia o repo inteiro, incluindo o projects.json gerado

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
